export const topics = [
    { id: 1, title: "Integers", path: "/integers" },
    { id: 2, title: "Address", path: "/address" },
    { id: 3, title: "Structs", path: "/structs" },
    { id: 4, title: "Functions", path: "/functions" },
    { id: 5, title: "Getters", path: "/getters" },
    { id: 6, title: "A Simple Counter", path: "/simple-counter" },
    { id: 7, title: "If Statements", path: "/if-statements" },
    { id: 8, title: "Loops", path: "/loops" },
    { id: 9, title: "Current Time", path: "/time" },
    { id: 10, title: "Bools", path: "/bools" },
    { id: 11, title: "Variables", path: "/variables" },
    { id: 12, title: "Null", path: "/null" },
    { id: 13, title: "Match", path: "/match" },
    { id: 14, title: "Match", path: "/match" },
    { id: 15, title: "Coins", path: "/coins" },
    { id: 16, title: "Sending TON", path: "/send-ton" },
    { id: 17, title: "Cells", path: "/cells" },
    { id: 18, title: "Tuples", path: "/tuples" },
    { id: 19, title: "Jettons", path: "/jettons" },
    { id: 20, title: "NFT", path: "/nft" },
];